apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-gpu-plugin
        volumeMounts:
        - name: kubeletcrt
          mountPath: /var/lib/kubelet/pki/kubelet.crt
      volumes:
      - name: kubeletcrt
        hostPath:
          path: /var/lib/kubelet/pki/kubelet.crt
          type: FileOrCreate
