bases:
  - ../../base
resources:
  - gpu-manager-rolebinding.yaml
  - gpu-manager-role.yaml
  - gpu-manager-sa.yaml
patches:
  - path: add-serviceaccount.yaml
  - path: add-podresource-mount.yaml
  - path: add-args.yaml
  - path: add-nodeselector-intel-gpu.yaml
  - path: add-kubelet-crt-mount.yaml
